server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://authenticationservice
          predicates:
            - Path=/api/auth/**
          filters:
            - JwtAuth # multiple patterns in ONE Path predicate

        - id: orders
          uri: lb://orderservice
          predicates:
            - Path=/api/orders/**
          filters:
            - JwtAuth

        - id: inventory
          uri: lb://inventoryservice
          predicates:
            - Path=/api/inventory/**
          filters:
            - JwtAuth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG