spring:
  application:
    name: authenticationservice

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:auth_service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update   # or validate if you use migrations

server:
  port: 8087

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET:change-me-32+chars-random}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true